;carrinho com lógica 1 na linha. Obstáculo detectado = 0.
;Para no cruzamento; espera tempo de atraso; acende o led do final.
;Fosc = 4MHz
LIST	    p=16F628A
#include    <p16f628a.inc>
__CONFIG _INTOSC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _BODEN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF
CBLOCK	    0X70
AT0	;
AT1	;
AT2	;AUXILIARES DO TEMPO DE ATRASO
ENDC
#DEFINE	M.ESQ	PORTB,4
#DEFINE M.DIR	PORTB,5
#DEFINE RM.ESQ	PORTB,6
#DEFINE RM.DIR	PORTB,7	    
#DEFINE S.DIR	PORTB,1	    ;	//  DE LINHA DIREITO
#DEFINE S.ESQ	PORTB,0	    ;	//  DE LINHA ESQUERDO
ORG	00
    GOTO    INICIO
ORG	04
    RETFIE
INICIO:
    BANKSEL	TRISB
    MOVLW	B'00000011'
    ;RB0:RB1 SENSORES FRENTE, RB4:RB7 SAIDA PARA MOTORES, RB3 PWM
    MOVWF	TRISB
    BANKSEL	CMCON
    MOVLW	0X07	    
    MOVWF	CMCON	    ;DESLIGAR MÓDULO COMPARADOR
;;;;PWM:
    BANKSEL PR2
    MOVLW   .124              ; PR2 = 124 para Fpwm ? 1.95kHz (Fosc=4MHz, prescaler 16)
    MOVWF   PR2
    BANKSEL CCP1CON
    MOVLW   B'00001100'       ; Modo PWM (CCP1CON = 0x0C)
    MOVWF   CCP1CON
    MOVLW   .70               ; Duty cycle de 50% (CCPR1L = 50)
    MOVWF   CCPR1L
    BANKSEL T2CON
    MOVLW   B'00000111'       ; Timer2 ligado, prescaler 1:16
    MOVWF   T2CON

    ;FIM DE CONFIG. PWM
    BANKSEL	TRISA	    
    CLRF	TRISA
    BANKSEL	PORTB
    CLRF	PORTB	    ;LIMPEZA DO PORTB
    CLRF	PORTA;;;;;
MAIN:
    MOVLW	B'00000011'
    ANDWF	PORTB,W	    ;ISOLAR OS BITS DOS SENSORES DE LINHA
    SUBLW	B'00000011'
    BTFSC	STATUS,Z    ;SE OS DOIS S. LINHA EM HIGH, CHAMA "CRUZAMENTO"
    CALL	CRUZAMENTO	    
;SENSOR NA LINHA = 1, SENSOR NA MESA = 0.
TE:
    BTFSS	S.ESQ	    ;TESTE SENSOR ESQ.
    ;BTFSC	S.DIR
    GOTO	SEGUE_E		;SE LIMPO
    GOTO	VOLTAR_E
TD:
    BTFSS	S.DIR	    ;TESTE SENSOR DIR
    ;BTFSC	S.ESQ
    GOTO	SEGUE_D		;SE LIMPO
    GOTO	VOLTAR_D
;;;;;;    
SEGUE_E:	    ;MOTOR ESQ PARA FRENTE
    
    BSF	    M.ESQ
    BCF	    RM.ESQ
    GOTO    TD
SEGUE_D:	    ;MOTOR DIR PARA FRENTE
    BSF	    M.DIR
    BCF	    RM.DIR
    GOTO    MAIN
VOLTAR_E:
    BCF	    RM.ESQ  ;MOTOR ESQUERDO PARA TRÁS
    BCF	    M.ESQ
    GOTO    TD
VOLTAR_D:
    BCF	    RM.DIR  ;MOTOR DIREITO PARA TRÁS
    BCF	    M.DIR
    GOTO    MAIN
CRUZAMENTO:;;;;;;;;TESTE
    bsf	    PORTA,3
    CALL    PARAR_M
    CALL    ATRASO
    ;GOTO    ACABOU
    CALL    ATRASO
    ;ANDAR UM POUCO PARA FRENTE PARA SENSOR DIREITO FICAR FORA DA LINHA
    CALL    PRA_FRENTE
    CALL    ATRASO
    CALL    CURVA_ESQ
_ESQ:
    BTFSS   S.DIR	;CURVA PARA ESQUERDA ATÉ S.DIR ACHAR LINHA
    GOTO    _ESQ
    RETURN		;VOLTA PARA SEGUIR LINHA
    
PARAR_M:
    BCF	    M.ESQ
    BCF	    M.DIR
    BCF	    RM.ESQ
    BCF	    RM.DIR
    RETURN

PRA_FRENTE:
    BSF	    M.ESQ
    BSF	    M.DIR
    RETURN
    
CURVA_ESQ:
    BSF	    M.ESQ
    BCF	    M.DIR
    BCF	    RM.ESQ
    BCF	    RM.DIR
    RETURN
ATRASO:;;;1 segundo para testes,AT2 = .4
    MOVLW   .1
    MOVWF   AT2
L2: MOVLW   .250
    MOVWF   AT1
L1: MOVLW   .250
    MOVWF   AT0
L0: NOP
    DECFSZ  AT0
    GOTO    L0	    ;1ms    
    DECFSZ  AT1
    GOTO    L1	    ;1ms X 250 = 250mS
    DECFSZ  AT2
    GOTO    L2	    ;250mS X 4 = 1s
    RETURN
ACABOU:
    CALL    PARAR_M
    BSF	    PORTB,2	;LED DO FINAL
    GOTO    ACABOU
   
END
